-- CasaStudent EU market seed. Safe to re-run: existing countries/cities are updated or skipped.
INSERT INTO public.countries (code,name,locale,currency,domain,active)
VALUES
('IE','Ireland','en-IE','EUR',NULL,true),
('UK','United Kingdom','en-GB','GBP',NULL,true),
('BE','Belgium','nl-BE','EUR',NULL,true),
('NL','Netherlands','nl-NL','EUR',NULL,true),
('DK','Denmark','da-DK','DKK',NULL,true),
('NO','Norway','nb-NO','NOK',NULL,true),
('SE','Sweden','sv-SE','SEK',NULL,true),
('FI','Finland','fi-FI','EUR',NULL,true),
('CZ','Czechia','cs-CZ','CZK',NULL,true),
('AT','Austria','de-AT','EUR',NULL,true),
('CH','Switzerland','de-CH','CHF',NULL,true),
('HU','Hungary','hu-HU','HUF',NULL,true),
('SK','Slovakia','sk-SK','EUR',NULL,true),
('RO','Romania','ro-RO','RON',NULL,true),
('BG','Bulgaria','bg-BG','EUR',NULL,true),
('GR','Greece','el-GR','EUR',NULL,true),
('EE','Estonia','et-EE','EUR',NULL,true),
('LV','Latvia','lv-LV','EUR',NULL,true),
('LT','Lithuania','lt-LT','EUR',NULL,true),
('AL','Albania','sq-AL','ALL',NULL,true),
('AD','Andorra','ca-AD','EUR',NULL,true),
('BY','Belarus','be-BY','BYN',NULL,true),
('BA','Bosnia and Herzegovina','bs-BA','BAM',NULL,true),
('HR','Croatia','hr-HR','EUR',NULL,true),
('CY','Cyprus','el-CY','EUR',NULL,true),
('IS','Iceland','is-IS','ISK',NULL,true),
('XK','Kosovo','sq-XK','EUR',NULL,true),
('LU','Luxembourg','lb-LU','EUR',NULL,true),
('MT','Malta','mt-MT','EUR',NULL,true),
('MD','Moldova','ro-MD','MDL',NULL,true),
('MC','Monaco','fr-MC','EUR',NULL,true),
('ME','Montenegro','sr-ME','EUR',NULL,true),
('MK','North Macedonia','mk-MK','MKD',NULL,true),
('RS','Serbia','sr-RS','RSD',NULL,true),
('SI','Slovenia','sl-SI','EUR',NULL,true),
('TR','Türkiye','tr-TR','TRY',NULL,true),
('UA','Ukraine','uk-UA','UAH',NULL,true),
('VA','Vatican City','la-VA','EUR',NULL,true),
('SM','San Marino','it-SM','EUR',NULL,true),
('LI','Liechtenstein','de-LI','CHF',NULL,true),
('RU','Russia','ru-RU','RUB',NULL,true),
('AM','Armenia','hy-AM','AMD',NULL,true),
('AZ','Azerbaijan','az-AZ','AZN',NULL,true),
('GE','Georgia','ka-GE','GEL',NULL,true)
ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, locale=EXCLUDED.locale, currency=EXCLUDED.currency, active=true;

UPDATE public.countries SET active=true, domain=NULL WHERE code='PT';
UPDATE public.cities SET active=true WHERE country_code='PT';

INSERT INTO public.cities (country_code,slug,name,active)
SELECT v.code,v.slug,v.name,true
FROM (VALUES
('IE','dublin','Dublin'),
('IE','cork','Cork'),
('IE','galway','Galway'),
('IE','limerick','Limerick'),
('UK','london','London'),
('UK','manchester','Manchester'),
('UK','edinburgh','Edinburgh'),
('UK','bristol','Bristol'),
('UK','leeds','Leeds'),
('BE','brussels','Brussels'),
('BE','leuven','Leuven'),
('BE','ghent','Ghent'),
('BE','antwerp','Antwerp'),
('BE','liege','Liège'),
('NL','amsterdam','Amsterdam'),
('NL','rotterdam','Rotterdam'),
('NL','utrecht','Utrecht'),
('NL','groningen','Groningen'),
('NL','leiden','Leiden'),
('DK','copenhagen','Copenhagen'),
('DK','aarhus','Aarhus'),
('DK','odense','Odense'),
('DK','aalborg','Aalborg'),
('NO','oslo','Oslo'),
('NO','bergen','Bergen'),
('NO','trondheim','Trondheim'),
('NO','stavanger','Stavanger'),
('SE','stockholm','Stockholm'),
('SE','lund','Lund'),
('SE','uppsala','Uppsala'),
('SE','gothenburg','Gothenburg'),
('SE','malmo','Malmö'),
('FI','helsinki','Helsinki'),
('FI','turku','Turku'),
('FI','tampere','Tampere'),
('FI','oulu','Oulu'),
('CZ','prague','Prague'),
('CZ','brno','Brno'),
('CZ','olomouc','Olomouc'),
('CZ','ostrava','Ostrava'),
('AT','vienna','Vienna'),
('AT','graz','Graz'),
('AT','innsbruck','Innsbruck'),
('AT','salzburg','Salzburg'),
('AT','linz','Linz'),
('CH','zurich','Zurich'),
('CH','geneva','Geneva'),
('CH','lausanne','Lausanne'),
('CH','basel','Basel'),
('CH','bern','Bern'),
('HU','budapest','Budapest'),
('HU','szeged','Szeged'),
('HU','debrecen','Debrecen'),
('HU','pecs','Pécs'),
('SK','bratislava','Bratislava'),
('SK','kosice','Košice'),
('SK','zilina','Žilina'),
('RO','bucharest','Bucharest'),
('RO','cluj-napoca','Cluj-Napoca'),
('RO','timisoara','Timișoara'),
('RO','iasi','Iași'),
('RO','brasov','Brașov'),
('BG','sofia','Sofia'),
('BG','plovdiv','Plovdiv'),
('BG','varna','Varna'),
('BG','veliko-tarnovo','Veliko Tarnovo'),
('GR','athens','Athens'),
('GR','thessaloniki','Thessaloniki'),
('GR','patras','Patras'),
('GR','heraklion','Heraklion'),
('GR','ioannina','Ioannina'),
('EE','tallinn','Tallinn'),
('EE','tartu','Tartu'),
('LV','riga','Riga'),
('LV','daugavpils','Daugavpils'),
('LT','vilnius','Vilnius'),
('LT','kaunas','Kaunas'),
('LT','klaipeda','Klaipėda'),
('AL','tirana','Tirana'),
('AL','durres','Durrës'),
('AL','shkoder','Shkodër'),
('AD','andorra-la-vella','Andorra la Vella'),
('BY','minsk','Minsk'),
('BY','brest','Brest'),
('BY','gomel','Gomel'),
('BA','sarajevo','Sarajevo'),
('BA','banja-luka','Banja Luka'),
('BA','mostar','Mostar'),
('HR','zagreb','Zagreb'),
('HR','split','Split'),
('HR','rijeka','Rijeka'),
('HR','osijek','Osijek'),
('CY','nicosia','Nicosia'),
('CY','limassol','Limassol'),
('CY','larnaca','Larnaca'),
('IS','reykjavik','Reykjavík'),
('IS','akureyri','Akureyri'),
('XK','pristina','Pristina'),
('XK','prizren','Prizren'),
('LU','luxembourg-city','Luxembourg City'),
('LU','esch-sur-alzette','Esch-sur-Alzette'),
('MT','msida','Msida'),
('MT','valletta','Valletta'),
('MD','chisinau','Chișinău'),
('MD','balti','Bălți'),
('MC','monaco','Monaco'),
('ME','podgorica','Podgorica'),
('ME','cetinje','Cetinje'),
('MK','skopje','Skopje'),
('MK','bitola','Bitola'),
('RS','belgrade','Belgrade'),
('RS','novi-sad','Novi Sad'),
('RS','nis','Niš'),
('SI','ljubljana','Ljubljana'),
('SI','maribor','Maribor'),
('TR','istanbul','Istanbul'),
('TR','ankara','Ankara'),
('TR','izmir','İzmir'),
('TR','eskisehir','Eskişehir'),
('UA','kyiv','Kyiv'),
('UA','lviv','Lviv'),
('UA','kharkiv','Kharkiv'),
('UA','odesa','Odesa'),
('VA','vatican-city','Vatican City'),
('SM','san-marino','San Marino'),
('LI','vaduz','Vaduz'),
('RU','moscow','Moscow'),
('RU','saint-petersburg','Saint Petersburg'),
('RU','kazan','Kazan'),
('AM','yerevan','Yerevan'),
('AM','gyumri','Gyumri'),
('AZ','baku','Baku'),
('AZ','ganja','Ganja'),
('GE','tbilisi','Tbilisi'),
('GE','kutaisi','Kutaisi'),
('GE','batumi','Batumi')
) AS v(code,slug,name)
WHERE NOT EXISTS (
  SELECT 1 FROM public.cities c WHERE c.country_code=v.code AND c.slug=v.slug
);
